### ISSUE TITLE
请求适配 QQ-Bot

### ISSUE THREAD

**Issue by Sakura1618** [zhiyu1998/yunzai-plugin-deer-pipe#1]
请求适配 QQ-Bot
```
TypeError: Cannot read properties of undefined (reading '1')
    at generateImage (file:///D:/QQbot/TRSS/Yunzai/plugins/yunzai-plugin-deer-pipe/utils/core.js:100:25)
    at DeerPipe.lu (file:///D:/QQbot/TRSS/Yunzai/plugins/yunzai-plugin-deer-pipe/apps/core.js:121:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///D:/QQbot/TRSS/Yunzai/lib/plugins/loader.js:262:41) {
  [stack]: "TypeError: Cannot read properties of undefined (reading '1')\n" +
    '    at generateImage (file:///D:/QQbot/TRSS/Yunzai/plugins/yunzai-plugin-deer-pipe/utils/core.js:100:25)\n' +
    '    at DeerPipe.lu (file:///D:/QQbot/TRSS/Yunzai/plugins/yunzai-plugin-deer-pipe/apps/core.js:121:27)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PluginsLoader.deal (file:///D:/QQbot/TRSS/Yunzai/lib/plugins/loader.js:262:41)',
  [message]: "Cannot read properties of undefined (reading '1')"
}
```

**Comment by zhiyu1998** [comment]
有人提出过，但是没看懂，需要一个关键PR，如果你会能测试成功可以尝试下，下面是参考例子：

1. https://gitee.com/kyrzy0416/yunzai-plugin-deer-pipe/pulls/2
2. https://gitee.com/kyrzy0416/yunzai-plugin-deer-pipe/pulls/1

关键PR例子：

![image](https://github.com/user-attachments/assets/92d6b2df-8e40-4a13-86b9-5c85c5915f6a)
